:sparkles: feat: Spring Security 인증 인가 처리 및 password 암호화 기능 추가
SMUMC-6th/6th_SPRING pull request #144
Opened 2024-05-18 15:16 UTC by Properks

- Spring Security 인증 인가 처리
- password 암호화 기능 추가

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #143 

## 📌 개요
- Spring Security 인증 인가 처리
- password 암호화 기능 추가

## 🔁 변경 사항
1754729d21096f9c7a3295366b2c611621f99d81
- Spring Security 인증 인가 처리
- password 암호화 기능 추가

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-05-21 00:35 UTC, catturtle123 requested changes

2024-05-21 00:35 UTC, catturtle123 commented on src/main/java/com/example/umc/study/config/SecurityConfig.java
> +                        .requestMatchers("/api/v1/posts/**").permitAll()
이 부분 allowurl에 있으니 지워주세요!

2024-05-21 00:35 UTC, catturtle123 commented on src/main/java/com/example/umc/study/config/SecurityConfig.java
> +                        .requestMatchers("/api/v1/replies/**").permitAll()
여기도요!

2024-05-22 01:52 UTC, Properks commented on src/main/java/com/example/umc/study/config/SecurityConfig.java
> +                        .requestMatchers("/api/v1/replies/**").permitAll()
allow url 중복 부분 수정했습니다!

2024-05-22 08:17 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-05-23 04:53 UTC, merged