:sparkles: Feat: 엔티티 생성 및 스웨거 설정
SMUMC-6th/6th_SPRING pull request #32
Opened 2024-03-31 11:56 UTC by kimdavid0521

- 엔티티 생성
- 스웨거 설정

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [x] 버그 수정
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [x] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #29 

## 📌 개요
- 엔티티 생성 및 스웨거 설정

## 🔁 변경 사항
- 엔티티 생성 및 스웨거 설정

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-03-31 15:14 UTC, catturtle123 requested changes
변경 사항 위에 커밋 기록과 연결 시켜 주시고 pr 타입은 해당하는 pr 타입만 선택하여주세요! 
그리고 이슈에 깃모지 붙여주세요!

2024-03-31 15:17 UTC, catturtle123 requested changes

2024-03-31 15:17 UTC, catturtle123 commented on src/main/java/com/example/umc/study/domain/Category.java
> +
각 클래스에 Builder 어노테이션을 붙여주세요!

2024-03-31 15:17 UTC, catturtle123 commented on src/main/java/com/example/umc/study/domain/Category.java
> +
Long id 위에 전부 띄워쓰기가 되어 있는데 전부 없애주세요

2024-03-31 15:25 UTC, kimdavid0521 commented on src/main/java/com/example/umc/study/domain/Category.java
> +
수정했습니다!

2024-03-31 15:26 UTC, catturtle123 commented
> 변경 사항 위에 커밋 기록과 연결 시켜 주시고 pr 타입은 해당하는 pr 타입만 선택하여주세요! 그리고 이슈에 깃모지 붙여주세요!

@kimdavid0521 이거도 확인 해주세요!

2024-03-31 16:15 UTC, kimdavid0521 commented
> > 변경 사항 위에 커밋 기록과 연결 시켜 주시고 pr 타입은 해당하는 pr 타입만 선택하여주세요! 그리고 이슈에 깃모지 붙여주세요!
> 
> @kimdavid0521 이거도 확인 해주세요!
수정 했습니다!

2024-04-01 03:02 UTC, catturtle123 approved these changes
넵! 고생많으셨습니다! merge 후에 issue 닫아주시고 branch 삭제 시켜주세요!

2024-04-07 11:56 UTC, merged