Feat/#53
SMUMC-6th/6th_SPRING pull request #54
Opened 2024-04-05 11:32 UTC by moonyaeyoon

## 📍 PR 타입 (하나 이상 선택)
- [O] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #53

## 📌 개요
- 

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-04-06 11:24 UTC, catturtle123 requested changes
변경 사항에 커밋을 넣어주세요!
다음은 질문에 대한 답변입니다.
1. 맞습니다 나중에 실 사용 시에는 DTO(혹은 넣을 내용)를 안에 넣는 것입니다!
2. 최대한 실 사용과 비슷하게 하려고 그렇게 하였습니다! (현재 사실상 필요 없는 코드는 맞습니다)
3. error일 때 result가 나오지 않는 이유가 궁금한 것인가요?

2024-04-06 12:15 UTC, moonyaeyoon commented
> 변경 사항에 커밋을 넣어주세요! 다음은 질문에 대한 답변입니다.
> 
> 1. 맞습니다 나중에 실 사용 시에는 DTO(혹은 넣을 내용)를 안에 넣는 것입니다!
> 2. 최대한 실 사용과 비슷하게 하려고 그렇게 하였습니다! (현재 사실상 필요 없는 코드는 맞습니다)
> 3. error일 때 result가 나오지 않는 이유가 궁금한 것인가요?

네 ,,! 2번에서는 result를 써줬는데 실제로는 안나오는 것 같아서요,,!

2024-04-06 12:57 UTC, catturtle123 commented
> > 변경 사항에 커밋을 넣어주세요! 다음은 질문에 대한 답변입니다.
> > 
> > 1. 맞습니다 나중에 실 사용 시에는 DTO(혹은 넣을 내용)를 안에 넣는 것입니다!
> > 2. 최대한 실 사용과 비슷하게 하려고 그렇게 하였습니다! (현재 사실상 필요 없는 코드는 맞습니다)
> > 3. error일 때 result가 나오지 않는 이유가 궁금한 것인가요?
> 
> 네 ,,! 2번에서는 result를 써줬는데 실제로는 안나오는 것 같아서요,,!
>
> 우선 RestController에서 error가 나면 RestControllerAdvice에서 감지해서 맞는 exception의 메소드를 날리게 됩니다. 2번에서 error안에 넣은 것은 StatusCode로 코드를 열어보면 onFailure에 code를 넣고 data는 null로 body를 만드는 것을 알 수 있습니다!
![스크린샷 2024-04-06 215505](https://github.com/SMUMC-6th/6th_SPRING/assets/101050942/9c1c89ee-b599-459f-89c1-597dca6adf53)

2024-04-08 04:51 UTC, moonyaeyoon commented
@catturtle123  답변감사합니다 ㅎㅎ ! 제가 변경사항에 커밋을 계속 빠뜨리고 있었네요,,!
변경했습니다!

2024-04-08 05:18 UTC, catturtle123 requested changes
mapping 테이블에도 createAt과 updateat을 붙여주세요!

2024-04-08 07:58 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-04-08 07:58 UTC, merged