:sparkles: Feat: User, Post, Reply 도메인 CRD 기능 구현
SMUMC-6th/6th_SPRING pull request #71
Opened 2024-04-10 19:06 UTC by chamm99

- User 도메인 CRD 기능 구현
- Post 도메인 CRD 기능 구현
- Reply 도메인 CRD 기능 구현

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #70

## 📌 개요
- User 도메인 CRD 기능 구현
- Post 도메인 CRD 기능 구현
- Reply 도메인 CRD 기능 구현

## 🔁 변경 사항
89b538c5de276986183c069b1e07817304ac073c
- User 도메인 CRD 기능 구현
- Post 도메인 CRD 기능 구현
- Reply 도메인 CRD 기능 구현

## 📸 스크린샷
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f1912130-0409-4e90-a90f-6091ae253e73/488a5bd2-3303-4faa-a402-8001cc3fd035/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f1912130-0409-4e90-a90f-6091ae253e73/9910316c-df86-4ec9-84d9-785f640efd92/Untitled.png)
![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f1912130-0409-4e90-a90f-6091ae253e73/a53b8e2d-6c50-48cf-bedb-035386115d51/Untitled.png)

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-04-13 15:23 UTC, catturtle123 requested changes

2024-04-13 15:23 UTC, catturtle123 commented on src/main/java/com/example/umc/study/service/impl/UserServiceImpl.java
> +    @Override
@Transactional 붙여주세요!

2024-04-13 15:23 UTC, catturtle123 commented on src/main/java/com/example/umc/study/service/impl/PostServiceImpl.java
> +    public void deletePost(Long postId) {
@Transactional 붙여주세요!

2024-04-14 06:13 UTC, chamm99 commented on src/main/java/com/example/umc/study/service/impl/PostServiceImpl.java
> +    public void deletePost(Long postId) {
수정하였습니다! 확인 부탁드립니다!

2024-04-14 06:40 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-04-14 08:06 UTC, merged