[Feat] CRUD 중 CRD 구현
SMUMC-6th/6th_SPRING pull request #88
Opened 2024-04-29 05:31 UTC by moonyaeyoon

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #85 

## 📌 개요
- CRUD 중 CRD 구현

## 🔁 변경 사항
- create : 9d00530
- read : 422930f
- delete : aebdd25
## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.

2024-04-29 05:34 UTC, catturtle123 requested changes
issue와 pull request의 Assignment 예닝님 것으로 바꾸고 User와 같은 양식으로 Post와 Reply도 crud 기능 추가해주세요!

2024-04-30 12:31 UTC, moonyaeyoon commented
앗 아직 하는 중인데 그냥 나눠서 커밋 날렸습니다 ..! 헷갈릴 것 같으니까 한번에 날릴게요..!

2024-05-01 03:00 UTC, moonyaeyoon commented
> 아닙니다! 따로 날려도 됩니다! 오해를 했었네요... 죄송합니다...

다 했습니다,,! 검사해주시면 될 것 같아요 ,,!!

2024-05-01 05:13 UTC, catturtle123 requested changes
리뷰 완료하였습니다. 확인하여주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/JPAtest/JpaTest.java
> +package com.example.umc.study.JPAtest;
이 클래스는 삭제 시켜주세요!

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @GetMapping("/users/{userId}")
users/{userId}/posts로 url을 바꾸어주세요!

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @PostMapping("/{userId}")
users/{userId}/posts 로 바꾸어주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @GetMapping("/list")
list는 없어도 될 것 같습니다.

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @DeleteMapping("/delete/{postId}")
delete/{postId}에서 delete는 빼주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @PostMapping("/{userId}/{postId}")
users/{userId}/posts/{postId}/replies 로 해주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @GetMapping("/posts/{postId}")
/posts/{postId}/replies로 해주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @DeleteMapping("/delete/{replyId}")
/delete/ 없애주세요

2024-05-01 05:13 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @GetMapping("/list")
list 없애주세요

2024-05-01 10:12 UTC, catturtle123 approved these changes
넵! 고생하셨습니다! 지금 commit에 fix인데 sparkles 깃모지를 쓰셔서 다음 부터는 각 커밋에 맞는 깃모지를 써주세요!

2024-05-02 00:13 UTC, merged