✨ Feat: CRUD 중 CRD 기능 구현
SMUMC-6th/6th_SPRING pull request #89
Opened 2024-04-29 12:20 UTC by jinho7

## 📍 PR 타입 (하나 이상 선택)
- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #87 

## 📌 개요
- ✨ Feat: CRUD 중 CRD 기능 구현

## 🔁 변경 사항
[f2d2ee5](https://github.com/SMUMC-6th/6th_SPRING/pull/89/commits/f2d2ee5f447e639d267a35b25ba4ee5d8f4f2dab)
User, Post, Reply 의 CRD 기능 구현

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [x] PR 템플릿에 맞추어 작성했어요.
- [x] 변경 내용에 대한 테스트를 진행했어요.
- [x] 프로그램이 정상적으로 동작해요.
- [x] PR에 적절한 라벨을 선택했어요.
- [x] 불필요한 코드는 삭제했어요.

2024-04-30 04:59 UTC, catturtle123 requested changes
그리고 변경사항 연결하여주세요!

2024-04-30 04:59 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @PostMapping("/replies/{replyId}")
replyId를 붙인 이유가 있나요?

2024-04-30 04:59 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/UserController.java
> +    @GetMapping("/{userId}")
users 붙여주세요!

2024-04-30 04:59 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/UserController.java
> +    @DeleteMapping("/{userId}")
여기도요!

2024-05-01 07:21 UTC, jinho7 commented on src/main/java/com/example/umc/study/controller/UserController.java
> +    @DeleteMapping("/{userId}")
[efd0d49](https://github.com/SMUMC-6th/6th_SPRING/pull/89/commits/efd0d493102b0f0e0919ec8fc4f89dc55669d3eb)
수정했습니다!

2024-05-01 07:21 UTC, jinho7 commented on src/main/java/com/example/umc/study/controller/UserController.java
> +    @GetMapping("/{userId}")
[efd0d49](https://github.com/SMUMC-6th/6th_SPRING/pull/89/commits/efd0d493102b0f0e0919ec8fc4f89dc55669d3eb)
수정했습니다.

2024-05-01 07:26 UTC, jinho7 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @PostMapping("/replies/{replyId}")
user 복사하다가 잘못 넣은 것 같네요 ㅜㅜ 죄송합니다
[40cf7a5](https://github.com/SMUMC-6th/6th_SPRING/pull/89/commits/40cf7a50e25c579d2eec281b3c57121326715561)
수정했습니다.

2024-05-01 07:36 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/ReplyController.java
> +    @PostMapping("/replies/{replyId}")
넵! 고생하셨습니다!

2024-05-01 07:38 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-05-02 05:47 UTC, merged