:sparkles: Feat: CRUD 중 CRD 기능 구현
SMUMC-6th/6th_SPRING pull request #91
Opened 2024-04-30 09:04 UTC by kimdavid0521

- CRUD 중 CRD 기능 구현
- 응답 통일 설정

## 📍 PR 타입 (하나 이상 선택)
- [o] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
Close #

## 📌 개요
- 

## 🔁 변경 사항

## 📸 스크린샷

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [o] PR 템플릿에 맞추어 작성했어요.
- [o] 변경 내용에 대한 테스트를 진행했어요.
- [o] 프로그램이 정상적으로 동작해요.
- [o] PR에 적절한 라벨을 선택했어요.
- [o] 불필요한 코드는 삭제했어요.

2024-04-30 10:25 UTC, catturtle123 requested changes
post와 reply도 구현하여주세요

2024-04-30 10:25 UTC, catturtle123 commented on src/main/java/com/example/umc/study/service/impl/UserServiceImpl.java
> +
Override와 Transactional을 붙여주세요

2024-04-30 10:25 UTC, catturtle123 commented on src/main/java/com/example/umc/study/service/impl/UserServiceImpl.java
> +
여기도요!

2024-04-30 10:43 UTC, catturtle123 commented
그리고 pull request 템플릿 잘 써주세요

2024-05-01 13:49 UTC, catturtle123 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @PostMapping("/api/v1/post")
post를 posts로 바꾸어주세요!

2024-05-01 13:53 UTC, kimdavid0521 commented on src/main/java/com/example/umc/study/controller/PostController.java
> +    @PostMapping("/api/v1/post")
수정했습니다!

2024-05-01 13:53 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-05-02 06:55 UTC, merged